import type { Metadata } from "next";
import {
	Archivo,
	Bricolage_Grotesque,
	Geist,
	Geist_Mono,
} from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Bricolage_Grotesque({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Head>
			<meta name="viewport" content="width=device-width,initial-scale=0.8,maximum-scale=0.8" />

			</Head>
			<body className={`${geistSans.className} antialiased`}>{children}</body>
		</html>
	);
}
