import type { Metadata } from "next";
import {
	Bricolage_Grotesque,
} from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Bricolage_Grotesque({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});



export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// function downloadCSV(filename, data) {
//   // 1) extract headers (keys)
//   const header = Object.keys(data[0]);

//   // 2) convert each object to array of values
//   const rows = data.map(obj => Object.values(obj));

//   // 3) build CSV string
//   const csv =
//     [header, ...rows]
//       .map(row => row.join(","))
//       .join("\n");

//   // 4) create CSV downloadable file
//   const blob = new Blob([csv], { type: "text/csv" });
//   const url = URL.createObjectURL(blob);

//   // 5) trigger download
//   const a = document.createElement("a");
//   a.href = url;
//   a.download = filename;
//   a.click();

//   // 6) cleanup
//   URL.revokeObjectURL(url);
// }

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Head>
			<meta name="viewport" content="width=device-width,initial-scale=0.8,maximum-scale=0.8" />

			</Head>
			<body className={`${geistSans.className} antialiased`}>
				{children}
					<Toaster position="top-center" />
				</body>
		</html>
	);
}
